#ifndef SANE_COMMON_HPP
#define SANE_COMMON_HPP

#endif //SANE_COMMON_HPP

#define MISSING_VALUE "N/A"
#define YOUTUBE_CHANNEL_PREFIX "UC"
#define YOUTUBE_UPLOADS_PLAYLIST_PREFIX "UU"
#define YOUTUBE_FAVOURITES_PLAYLIST_PREFIX "FL"
#define YOUTUBE_LIKES_PLAYLIST_PREFIX "LL"